### ISSUE TITLE
I encountered a bug in training

### ISSUE THREAD

**Issue by Adong-1209** [sebgao/LIP#12]
![捕获1](https://user-images.githubusercontent.com/90688177/134469944-e78f5e12-3c8c-444a-bf5c-4e0a6a13f4c8.PNG)

**Comment by sebgao** [comment]
It seems a problem of higher version PyTorch compatibility about CUDA interface. Since I write CUDA implementation of LIP in PyTorch v1.0, it is highly recommended to run experiments with PyTorch v1.0. Could you please provide the detailed version of your PyTorch?
If you like to stick with a higher version of PyTorch, an alternative way is to use the implementation of LIP consisting up of PyTorch primitives.

**Comment by Adong-1209** [comment]
My pytorch version is 1.8. If I don't change the version, what should I do now

**Comment by sebgao** [comment]
You could use either https://github.com/sebgao/LIP/blob/ea0631e8776c058defa5f330abd5dc7eb47ff2ce/cuda-lip/LIP/pyinterface.py#L41
or
https://github.com/sebgao/LIP/blob/ea0631e8776c058defa5f330abd5dc7eb47ff2ce/imagenet/lip_resnet.py#L19
for your code. It is based on PyTorch primitives and free from the version compatibility problem.

**Comment by sebgao** [comment]
If you have installed CUDA-LIP library already, you can simply call `LIP.primitive_lip2d(x, logit, ...)` instead of `LIP.cuda_lip2d(...)` to perform LIP.

**Comment by Adong-1209** [comment]
The above error occurred when I used lip.cuda_lip2d. Now I use lip.primitive_Lip2d can run successfully. If there is any problem in the follow-up, I will consult again. Thanks for your help.
